/* AUTO-GENERATED by .github/workflows/sync-portfolio.yml — do not edit by hand. */
const GITHUB_REPOS = [
  {
    "name": "agentic-dev-flow",
    "description": "",
    "url": "https://github.com/VivekArora1107/agentic-dev-flow",
    "language": "HTML",
    "stars": 0,
    "updated": "2026-06-22"
  },
  {
    "name": "Capstone-Project",
    "description": "",
    "url": "https://github.com/VivekArora1107/Capstone-Project",
    "language": "Jupyter Notebook",
    "stars": 1,
    "updated": "2025-04-09"
  },
  {
    "name": "tableau",
    "description": "This repository contains some exploratory data analysis projects (inc. python, tablue, SQL and Power BI",
    "url": "https://github.com/VivekArora1107/tableau",
    "language": "",
    "stars": 0,
    "updated": "2025-01-15"
  },
  {
    "name": "Machine-Learning-Project---Predicting-New-York-City-Taxi-Fare",
    "description": "",
    "url": "https://github.com/VivekArora1107/Machine-Learning-Project---Predicting-New-York-City-Taxi-Fare",
    "language": "Jupyter Notebook",
    "stars": 0,
    "updated": "2025-01-07"
  },
  {
    "name": "Gradient-Boosting-with-XGBoost",
    "description": "Gradient Boosting with XGBoost - Rossman Sales Dataset",
    "url": "https://github.com/VivekArora1107/Gradient-Boosting-with-XGBoost",
    "language": "Jupyter Notebook",
    "stars": 0,
    "updated": "2025-01-04"
  },
  {
    "name": "Machine-Learning",
    "description": "",
    "url": "https://github.com/VivekArora1107/Machine-Learning",
    "language": "Jupyter Notebook",
    "stars": 0,
    "updated": "2024-12-27"
  },
  {
    "name": "R",
    "description": "",
    "url": "https://github.com/VivekArora1107/R",
    "language": "",
    "stars": 0,
    "updated": "2024-12-27"
  },
  {
    "name": "SAS",
    "description": "",
    "url": "https://github.com/VivekArora1107/SAS",
    "language": "HTML",
    "stars": 0,
    "updated": "2024-12-27"
  },
  {
    "name": "Exploratory-Data-Analysis",
    "description": "",
    "url": "https://github.com/VivekArora1107/Exploratory-Data-Analysis",
    "language": "Jupyter Notebook",
    "stars": 0,
    "updated": "2024-12-25"
  }
];
