/* Regenerates github.js from the user's public GitHub repos.
   Run by .github/workflows/sync-portfolio.yml on a daily schedule.
   No auth needed to list public repos; Node 18+ has global fetch. */

import { writeFileSync } from 'node:fs';

const USER = process.env.GH_USER || 'vivekarora1107';
const SELF = (process.env.GITHUB_REPOSITORY || '').split('/')[1] || '';

// Repos to keep out of the auto strip: this portfolio repo, and anything
// already written up as a curated case study (edit this list as needed).
const EXCLUDE = new Set(
  [SELF, `${USER}.github.io`, 'knowledge-hub', 'Spotify-circles']
    .filter(Boolean)
    .map((s) => s.toLowerCase())
);

const res = await fetch(
  `https://api.github.com/users/${USER}/repos?per_page=100&sort=updated`,
  { headers: { Accept: 'application/vnd.github+json', 'User-Agent': USER } }
);

if (!res.ok) {
  console.error('GitHub API error:', res.status, await res.text());
  process.exit(1);
}

const repos = await res.json();

const items = repos
  .filter((r) => !r.fork && !r.archived && !r.private)
  .filter((r) => !EXCLUDE.has(String(r.name).toLowerCase()))
  .sort((a, b) => new Date(b.pushed_at) - new Date(a.pushed_at))
  .slice(0, 9)
  .map((r) => ({
    name: r.name,
    description: r.description || '',
    url: r.html_url,
    language: r.language || '',
    stars: r.stargazers_count || 0,
    updated: new Date(r.pushed_at).toISOString().slice(0, 10),
  }));

const banner =
  '/* AUTO-GENERATED by .github/workflows/sync-portfolio.yml — do not edit by hand. */\n';
writeFileSync(
  'github.js',
  banner + 'const GITHUB_REPOS = ' + JSON.stringify(items, null, 2) + ';\n'
);
console.log(`Wrote ${items.length} repos to github.js`);
